// Pure view-model for the dashboard's "today" card. No react-native import
// -- verified under `node --test` (src/recommendation.test.ts).
//
// The app only FORMATS and ADDS here. Every physiological / climate
// computation stays server-side: target pace comes from GET /guidance/today,
// the weather pace delta comes from GET /weather (app/weather_pace.py). This
// module never re-derives either.

import { formatPace, formatLoad } from './format.ts';

// Structural subsets of the api.ts response types -- kept local so this
// module has no dependency on api.ts (which imports react-native).
export interface GuidanceInput {
  local_date: string;
  recommendation: {
    workout_type: string;
    duration_minutes: number;
    distance_km: number | null;
    target_pace_sec_per_km: number | null;
    intensity_label: string;
    algorithm_version: string;
  };
  tone_text: string;
  tone_reviewed_by: string;
}

export interface WeatherInput {
  state: 'LIVE' | 'CACHED' | 'STALE' | 'UNAVAILABLE';
  temperature_c: number | null;
  humidity_pct: number | null;
  pace_adjustment_sec_per_km: number | null;
}

export interface RecommendationView {
  localDate: string;
  workoutType: string;
  intensityLabel: string;
  durationLabel: string;
  distanceLabel: string;
  targetPaceLabel: string;
  // Weather-adjusted pace: null when either input is missing -- callers
  // must render "unavailable", never fall back to the unadjusted pace.
  weatherAdjustedPaceLabel: string | null;
  weatherAdjustmentSeconds: number | null;
  toneText: string;
  // Disclaimer facts -- always surfaced next to the recommendation.
  deterministicEngine: true;
  algorithmVersion: string;
  toneReviewedBy: string;
  toneIsHumanReviewed: boolean;
}

export function buildRecommendationView(
  guidance: GuidanceInput,
  weather: WeatherInput | null,
): RecommendationView {
  const rec = guidance.recommendation;

  const targetPace = rec.target_pace_sec_per_km;
  const adjustment =
    weather && weather.state !== 'UNAVAILABLE'
      ? weather.pace_adjustment_sec_per_km
      : null;

  const canAdjust = targetPace != null && adjustment != null;
  const adjustedSeconds = canAdjust ? targetPace + adjustment : null;

  return {
    localDate: guidance.local_date,
    workoutType: rec.workout_type,
    intensityLabel: rec.intensity_label,
    durationLabel: `${rec.duration_minutes} min`,
    distanceLabel: rec.distance_km != null ? `${formatLoad(rec.distance_km)} km` : '--',
    targetPaceLabel: formatPace(targetPace),
    weatherAdjustedPaceLabel: adjustedSeconds != null ? formatPace(adjustedSeconds) : null,
    weatherAdjustmentSeconds: canAdjust ? adjustment : null,
    toneText: guidance.tone_text,
    deterministicEngine: true,
    algorithmVersion: rec.algorithm_version,
    toneReviewedBy: guidance.tone_reviewed_by,
    toneIsHumanReviewed: Boolean(guidance.tone_reviewed_by),
  };
}

export const RECOMMENDATION_DISCLAIMER: Record<'zh-TW' | 'en', string> = {
  'zh-TW':
    '以上數字由固定規則引擎計算，不由 AI 產生。搭配的教練語氣文字是從真人預先審核的字句中挑選，不是 AI 撰寫；你的個資與定位不會傳給任何文字生成服務。',
  en:
    'These numbers are computed by a fixed rule engine, not generated by AI. The coaching-tone message is selected from human-reviewed phrasing, not written by an AI, and your personal data and location are never sent to a text-generation service.',
};
